# Generated by Django 6.0.2 on 2026-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок",
                        max_length=200,
                        verbose_name="Заголовок статьи",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите содержание", verbose_name="Содержание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью статьи",
                        null=True,
                        upload_to="articles/",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
