# Generated by Django 6.0.2 on 2026-05-06 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "permissions": [
                    ("can_publish_article", "Может публиковать статьи"),
                    ("can_unpublish_article", "Может снимать с публикации статьи"),
                ],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
